[package]
name = "svc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.7.7"
hyper = "1.5.0"
serde_json = "1.0.132"
tokio = { version = "1.41.0", features = ["full"] }
